<a href="https://colab.research.google.com/github/Dyakonov/Colab/blob/main/dj_LBcrack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Взлом лидербода

In [ ]:
import numpy as np

In [ ]:
print (np.binary_repr(3, width=3))
k=2
M = np.zeros((2**k, 2**k))
print (M.shape)

011
(4, 4)


In [ ]:
def getM(k = 2, printmode=True):
  M = np.zeros((2**k, 2**k))

  for i in range(2**k):
    si = np.binary_repr(i, width=k)
    zi = np.array([int(x) for x in si])
    if printmode:
      print (si)
    for j in range(2**k):
      sj = np.binary_repr(j, width=k)
      zj = np.array([int(x) for x in sj])
      M[i, j] = sum(zi != zj)
  return M

getM(1)

0
1


array([[0., 1.],
       [1., 0.]])

In [ ]:
getM(2)

00
01
10
11


array([[0., 1., 1., 2.],
       [1., 0., 2., 1.],
       [1., 2., 0., 1.],
       [2., 1., 1., 0.]])

In [ ]:
getM(3)

000
001
010
011
100
101
110
111


array([[0., 1., 1., 2., 1., 2., 2., 3.],
       [1., 0., 2., 1., 2., 1., 3., 2.],
       [1., 2., 0., 1., 2., 3., 1., 2.],
       [2., 1., 1., 0., 3., 2., 2., 1.],
       [1., 2., 2., 3., 0., 1., 1., 2.],
       [2., 1., 3., 2., 1., 0., 2., 1.],
       [2., 3., 1., 2., 1., 2., 0., 1.],
       [3., 2., 2., 1., 2., 1., 1., 0.]])

In [ ]:
def getHfromM(M):
  n = M.shape[0]
  H = []
  for i in range(n-1):
    for j in range(i+1, n):
      print (i, j)
      z = M[i,:]!=M[j,:]
      if ~z.all():
        H.append(z)
  return(np.array(H)+0)

H = getHfromM(M)
print (H)

0 1
0 2
0 3
1 2
1 3
2 3
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
k = 2
M = getM(k)
H = getHfromM(M)
print (M)
print (H)

00
01
10
11
0 1
0 2
0 3
1 2
1 3
2 3
[[0. 1. 1. 2.]
 [1. 0. 2. 1.]
 [1. 2. 0. 1.]
 [2. 1. 1. 0.]]
[[1 0 0 1]
 [0 1 1 0]]


In [ ]:
k = 3
M = getM(k)
H = getHfromM(M)
print (M)
print (H)

000
001
010
011
100
101
110
111
0 1
0 2
0 3
0 4
0 5
0 6
0 7
1 2
1 3
1 4
1 5
1 6
1 7
2 3
2 4
2 5
2 6
2 7
3 4
3 5
3 6
3 7
4 5
4 6
4 7
5 6
5 7
6 7
[[0. 1. 1. 2. 1. 2. 2. 3.]
 [1. 0. 2. 1. 2. 1. 3. 2.]
 [1. 2. 0. 1. 2. 3. 1. 2.]
 [2. 1. 1. 0. 3. 2. 2. 1.]
 [1. 2. 2. 3. 0. 1. 1. 2.]
 [2. 1. 3. 2. 1. 0. 2. 1.]
 [2. 3. 1. 2. 1. 2. 0. 1.]
 [3. 2. 2. 1. 2. 1. 1. 0.]]
[[1 0 0 1 1 0 0 1]
 [1 0 1 0 0 1 0 1]
 [1 1 0 0 0 0 1 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 0 1]
 [0 0 1 1 1 1 0 0]
 [0 1 0 1 1 0 1 0]
 [1 0 0 1 1 0 0 1]
 [0 1 1 0 0 1 1 0]]


In [ ]:
w = H[:,:4] @ (2 ** np.arange(4))

I = np.argsort(w)

H[I, :4]

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 1]])

In [ ]:
k = 4
M = getM(k)
H = getHfromM(M)
print (M)
print (H)

0000
0001
0010
0011
0100
0101
0110
0111
1000
1001
1010
1011
1100
1101
1110
1111
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
3 4
3 5
3 6
3 7
3 8
3 9
3 10
3 11
3 12
3 13
3 14
3 15
4 5
4 6
4 7
4 8
4 9
4 10
4 11
4 12
4 13
4 14
4 15
5 6
5 7
5 8
5 9
5 10
5 11
5 12
5 13
5 14
5 15
6 7
6 8
6 9
6 10
6 11
6 12
6 13
6 14
6 15
7 8
7 9
7 10
7 11
7 12
7 13
7 14
7 15
8 9
8 10
8 11
8 12
8 13
8 14
8 15
9 10
9 11
9 12
9 13
9 14
9 15
10 11
10 12
10 13
10 14
10 15
11 12
11 13
11 14
11 15
12 13
12 14
12 15
13 14
13 15
14 15
[[0. 1. 1. 2. 1. 2. 2. 3. 1. 2. 2. 3. 2. 3. 3. 4.]
 [1. 0. 2. 1. 2. 1. 3. 2. 2. 1. 3. 2. 3. 2. 4. 3.]
 [1. 2. 0. 1. 2. 3. 1. 2. 2. 3. 1. 2. 3. 4. 2. 3.]
 [2. 1. 1. 0. 3. 2. 2. 1. 3. 2. 2. 1. 4. 3. 3. 2.]
 [1. 2. 2. 3. 0. 1. 1. 2. 2. 3. 3. 4. 1. 2. 2. 3.]
 [2. 1. 3. 2. 1. 0. 2. 1. 3. 2. 4. 3. 2. 1. 3. 2.]
 [2. 3. 1. 2. 1. 2. 0. 1. 3. 4. 2. 3. 2. 3. 

In [ ]:
w = H[:,:8] @ (2 ** np.arange(8))

I = np.argsort(w)

H[I, :8]

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1],
       [1,

In [ ]:
tmp1 = np.array([int(x) for x in '011']) #  == '101'
tmp2 = np.array([int(x) for x in '101'])
sum(tmp1 != tmp2)

2

In [ ]:
for i in range(H.shape[0]):
  #for j in range(H.shape[1]):
    print(H[i,:])

[1 0 0 1 1 0 0 1]
[1 0 1 0 0 1 0 1]
[1 1 0 0 0 0 1 1]
[0 1 1 0 0 1 1 0]
[0 1 0 1 1 0 1 0]
[1 1 0 0 0 0 1 1]
[0 0 1 1 1 1 0 0]
[1 0 1 0 0 1 0 1]
[0 0 1 1 1 1 0 0]
[0 1 0 1 1 0 1 0]
[1 0 0 1 1 0 0 1]
[0 1 1 0 0 1 1 0]


In [ ]:
(str(x) for x in H[0,:])

<generator object <genexpr> at 0x7ff4296e0660>

In [ ]:
print (str(H[:,:8]))

[[1 0 0 1 1 0 0 1]
 [1 0 1 0 0 1 0 1]
 [1 1 0 0 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 0 0 0 0]
 [1 1 1 0 1 0 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 0 0 0 0]
 [1 1 0 1 0 1 1 0]
 [0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 0 1 1 0 1 1 0]
 [1 1 1 1 0 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [0 1 1 1 1 0 0 1]
 [1 1 1 1 0 0 0 0]
 [1 0 0 1 1 0 0 1]
 [0 0 0 0 1 1 1 1]
 [1 0 0 1 1 1 1 0]
 [1 0 1 0 1 0 1 0]
 [1 1 0 0 1 1 0 0]
 [0 1 1 0 0 1 1 0]
 [0 0 0 0 1 1 1 1]
 [0 1 1 0 1 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 0]
 [0 1 1 0 1 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [1 0 0 1 1 0 0 1]
 [1 0 1 0 0 1 0 1]
 [1 1 0 0 0 0 1 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 0 1]
 [0 0 1 1 1 

In [ ]:
lst = [[2, 3, 4, 6],
[2, 3, 4, 7],
[2, 4, 5, 6],
[2, 5, 6, 7],
[3, 4, 5, 7],
[3, 5, 6, 7],
[1, 2, 3, 7],
[2, 4, 7, 8],
[1, 2, 5, 7],
[2, 6, 7, 8],
[1, 2, 3, 6],
[1, 2, 6, 8],
[3, 4, 6, 8],
[1, 3, 5, 6],
[3, 6, 7, 8],
[1, 3, 7, 8],
[1, 2, 4, 5],
[1, 2, 4, 8],
[1, 3, 4, 5],
[1, 3, 4, 8],
[4, 5, 6, 8],
[1, 5, 6, 8],
[4, 5, 7, 8],
[1, 5, 7, 8]]

In [ ]:
k

2

In [ ]:
for z in lst:
  print ("-----")
  for x in z:
    print (np.binary_repr(x-1, width=4)) # ТУТ -1 надо!!!

-----
0001
0010
0011
0101
-----
0001
0010
0011
0110
-----
0001
0011
0100
0101
-----
0001
0100
0101
0110
-----
0010
0011
0100
0110
-----
0010
0100
0101
0110
-----
0000
0001
0010
0110
-----
0001
0011
0110
0111
-----
0000
0001
0100
0110
-----
0001
0101
0110
0111
-----
0000
0001
0010
0101
-----
0000
0001
0101
0111
-----
0010
0011
0101
0111
-----
0000
0010
0100
0101
-----
0010
0101
0110
0111
-----
0000
0010
0110
0111
-----
0000
0001
0011
0100
-----
0000
0001
0011
0111
-----
0000
0010
0011
0100
-----
0000
0010
0011
0111
-----
0011
0100
0101
0111
-----
0000
0100
0101
0111
-----
0011
0100
0110
0111
-----
0000
0100
0110
0111


In [ ]:
M[np.array([0,1,2,4]),:]

array([[0., 1., 1., 2., 1., 2., 2., 3., 1., 2., 2., 3., 2., 3., 3., 4.],
       [1., 0., 2., 1., 2., 1., 3., 2., 2., 1., 3., 2., 3., 2., 4., 3.],
       [1., 2., 0., 1., 2., 3., 1., 2., 2., 3., 1., 2., 3., 4., 2., 3.],
       [1., 2., 2., 3., 0., 1., 1., 2., 2., 3., 3., 4., 1., 2., 2., 3.]])

In [ ]:
H[np.array([0,1,2,4]),:]

array([[1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1]])

In [ ]:
M[:, np.array([0,1,2,4])]

array([[0., 1., 1., 1.],
       [1., 0., 2., 2.],
       [1., 2., 0., 2.],
       [2., 1., 1., 3.],
       [1., 2., 2., 0.],
       [2., 1., 3., 1.],
       [2., 3., 1., 1.],
       [3., 2., 2., 2.],
       [1., 2., 2., 2.],
       [2., 1., 3., 3.],
       [2., 3., 1., 3.],
       [3., 2., 2., 4.],
       [2., 3., 3., 1.],
       [3., 2., 4., 2.],
       [3., 4., 2., 2.],
       [4., 3., 3., 3.]])

In [ ]:
H[:, np.array([0,1,2])]

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 0],
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0,

In [ ]:
H

array([[1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 1, 0]])

(1, 8)

In [ ]:
H = H[:,:8]
print (H)



[[1 0 0 1 1 0 0 1]
 [1 0 1 0 0 1 0 1]
 [1 1 0 0 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 0 0 0 0]
 [1 1 1 0 1 0 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 0]
 [1 1 1 1 0 0 0 0]
 [1 1 0 1 0 1 1 0]
 [0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 0 1 1 0 1 1 0]
 [1 1 1 1 0 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 1 0 1 1 0 1 0]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [0 1 1 1 1 0 0 1]
 [1 1 1 1 0 0 0 0]
 [1 0 0 1 1 0 0 1]
 [0 0 0 0 1 1 1 1]
 [1 0 0 1 1 1 1 0]
 [1 0 1 0 1 0 1 0]
 [1 1 0 0 1 1 0 0]
 [0 1 1 0 0 1 1 0]
 [0 0 0 0 1 1 1 1]
 [0 1 1 0 1 1 0 1]
 [0 1 0 1 0 1 0 1]
 [1 1 0 0 1 1 0 0]
 [0 1 1 0 1 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1 0]
 [1 0 0 1 0 1 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 0 1 0 1]
 [1 0 0 1 1 0 0 1]
 [1 0 1 0 0 1 0 1]
 [1 1 0 0 0 0 1 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 0 1 0 0 1 0 1]
 [0 0 1 1 1 

In [ ]:
S0 = np.zeros((1, H.shape[1]))
S0.shape

for j in range(H.shape[0]):
  I = S0[:, np.nonzero(H[j,:])[0]].any(axis=1)
  S1 = S0[I,:]
  lst = [S1]
  S0 = S0[~I,:]
  for x in list(np.nonzero(H[j,:])[0]):
    tmp = S0.copy()
    tmp[:, x] = 1
    lst.append(tmp)
  S0 = np.concatenate(lst, axis=0)

In [ ]:
print (S0)

[[1. 1. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 1. 1. ... 1. 0. 0.]
 ...
 [0. 1. 1. ... 1. 0. 0.]
 [0. 1. 1. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]]


In [ ]:
S0.shape

(272, 8)

In [ ]:
for i in range(10):
  print (S0[i,:])

[1. 1. 0. 1. 0. 1. 0. 0.]
[1. 0. 0. 1. 0. 1. 0. 1.]
[0. 1. 1. 1. 0. 1. 0. 0.]
[0. 0. 1. 1. 0. 1. 0. 1.]
[0. 1. 0. 1. 1. 1. 0. 0.]
[0. 0. 0. 1. 1. 1. 0. 1.]
[0. 1. 0. 1. 0. 1. 1. 0.]
[0. 0. 0. 1. 0. 1. 1. 1.]
[1. 0. 1. 1. 0. 0. 1. 0.]
[1. 0. 1. 1. 0. 0. 0. 1.]


In [ ]:
(S0 @ S0.T).shape

(272, 272)

In [ ]:
np.diag((S0 @ S0.T))

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4.

In [ ]:
w = S0 @ (2 ** np.arange(8))
I = np.argsort(w)
S0 = S0[I,:]

In [ ]:
w = S0 @ (2 ** np.arange(8))

In [ ]:
I = np.concatenate([np.ones(1)==1, np.diff(w)>0])

In [ ]:
S0 = S0[I,:]

In [ ]:
for i in range(S0.shape[0]):
  print (S0[i,:])

[1. 1. 1. 0. 1. 0. 0. 0.]
[1. 1. 0. 1. 1. 0. 0. 0.]
[1. 0. 1. 1. 1. 0. 0. 0.]
[0. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 1. 0. 0.]
[1. 1. 0. 1. 0. 1. 0. 0.]
[1. 0. 1. 1. 0. 1. 0. 0.]
[0. 1. 1. 1. 0. 1. 0. 0.]
[1. 0. 1. 0. 1. 1. 0. 0.]
[0. 1. 1. 0. 1. 1. 0. 0.]
[1. 0. 0. 1. 1. 1. 0. 0.]
[0. 1. 0. 1. 1. 1. 0. 0.]
[1. 1. 1. 0. 0. 0. 1. 0.]
[1. 1. 0. 1. 0. 0. 1. 0.]
[1. 0. 1. 1. 0. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 1. 0.]
[1. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 1. 0. 1. 0. 1. 0.]
[1. 0. 0. 1. 1. 0. 1. 0.]
[0. 0. 1. 1. 1. 0. 1. 0.]
[1. 1. 0. 0. 0. 1. 1. 0.]
[1. 0. 1. 0. 0. 1. 1. 0.]
[1. 0. 0. 1. 0. 1. 1. 0.]
[0. 1. 0. 1. 0. 1. 1. 0.]
[0. 0. 1. 1. 0. 1. 1. 0.]
[1. 0. 0. 0. 1. 1. 1. 0.]
[0. 1. 0. 0. 1. 1. 1. 0.]
[0. 0. 1. 0. 1. 1. 1. 0.]
[0. 0. 0. 1. 1. 1. 1. 0.]
[1. 1. 1. 0. 0. 0. 0. 1.]
[1. 1. 0. 1. 0. 0. 0. 1.]
[1. 0. 1. 1. 0. 0. 0. 1.]
[0. 1. 1. 1. 0. 0. 0. 1.]
[1. 1. 0. 0. 1. 0. 0. 1.]
[1. 0. 1. 0. 1. 0. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 1.]
[0. 1. 0. 1. 1. 0. 0. 1.]
[0. 0. 1. 1. 1. 0. 0. 1.]
[1. 1. 0. 0.

In [ ]:
for i in range(S0.shape[0]):
  print (S0[i,:])

[1. 1. 1. 0. 1. 0. 0. 0.]
[1. 1. 0. 1. 1. 0. 0. 0.]
[1. 0. 1. 1. 1. 0. 0. 0.]
[0. 1. 1. 1. 1. 0. 0. 0.]
[1. 1. 1. 0. 0. 1. 0. 0.]
[1. 1. 0. 1. 0. 1. 0. 0.]
[1. 0. 1. 1. 0. 1. 0. 0.]
[0. 1. 1. 1. 0. 1. 0. 0.]
[1. 0. 1. 0. 1. 1. 0. 0.]
[0. 1. 1. 0. 1. 1. 0. 0.]
[1. 0. 0. 1. 1. 1. 0. 0.]
[0. 1. 0. 1. 1. 1. 0. 0.]
[1. 1. 1. 0. 0. 0. 1. 0.]
[1. 1. 0. 1. 0. 0. 1. 0.]
[1. 0. 1. 1. 0. 0. 1. 0.]
[0. 1. 1. 1. 0. 0. 1. 0.]
[1. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 1. 0. 1. 0. 1. 0.]
[1. 0. 0. 1. 1. 0. 1. 0.]
[0. 0. 1. 1. 1. 0. 1. 0.]
[1. 1. 0. 0. 0. 1. 1. 0.]
[1. 0. 1. 0. 0. 1. 1. 0.]
[1. 0. 0. 1. 0. 1. 1. 0.]
[0. 1. 0. 1. 0. 1. 1. 0.]
[0. 0. 1. 1. 0. 1. 1. 0.]
[1. 0. 0. 0. 1. 1. 1. 0.]
[0. 1. 0. 0. 1. 1. 1. 0.]
[0. 0. 1. 0. 1. 1. 1. 0.]
[0. 0. 0. 1. 1. 1. 1. 0.]
[1. 1. 1. 0. 0. 0. 0. 1.]
[1. 1. 0. 1. 0. 0. 0. 1.]
[1. 0. 1. 1. 0. 0. 0. 1.]
[0. 1. 1. 1. 0. 0. 0. 1.]
[1. 1. 0. 0. 1. 0. 0. 1.]
[1. 0. 1. 0. 1. 0. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 1.]
[0. 1. 0. 1. 1. 0. 0. 1.]
[0. 0. 1. 1. 1. 0. 0. 1.]
[1. 1. 0. 0.

In [ ]:
Hlist = [[x for x in list(np.nonzero(H[j,:])[0])] for j in range(H.shape[0])]
Hlist

[[0, 3, 4, 7],
 [0, 2, 5, 7],
 [0, 1, 6, 7],
 [1, 2, 5, 6],
 [1, 3, 4, 6],
 [0, 1, 6, 7],
 [2, 3, 4, 5],
 [0, 2, 5, 7],
 [2, 3, 4, 5],
 [1, 3, 4, 6],
 [0, 3, 4, 7],
 [1, 2, 5, 6]]

In [ ]:
S0 = [set()]
for S in Hlist[:2]:
  S0 = [x | K for K in S0 for x in S]



S0


[{0},
 {0, 2},
 {0, 5},
 {0, 7},
 {0, 3},
 {2, 3},
 {3, 5},
 {3, 7},
 {0, 4},
 {2, 4},
 {4, 5},
 {4, 7},
 {0, 7},
 {2, 7},
 {5, 7},
 {7}]

In [ ]:
[{x} for x in list(np.nonzero(H[0,:])[0])]

[{0}, {3}, {4}, {7}]

In [ ]:
S = [{}]
S

[{}]

In [ ]:
{0,1,2} > {0, 3}

False